\documentclass{article}

\begin{document}

Here is the table:
  
  \begin{center}
  \begin{tabular}{rrrrrrrr}
  <<results='asis',echo=false>>=
  nr = 3; nc = 8
  x = matrix(format(round(rnorm(nr * nc), 2)), nc = nc)
  for (i in 1:nr)
    for(j in 1:nc) {
      cat("$", x[i,j], "$")
      if(j < nc)
        cat("&")
      else
        cat("\\\\\n")
    }
  @
  \end{tabular}
  \end{center}
  
\end{document}